# Generated by Django 4.1.4 on 2022-12-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_hat', '0002_rename_name_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
